# Site settings
title: Ryan Harden Personal Page
description: Ryan Harden custom developed Jeykll styling
url: https://airforcegrads.com/ryanharden/
baseurl: "/ryanharden"
permalink: blog/:year/:month/:day/:title/
future: true

# Author information
author:
  name: Ryan Joseph Albright Harden
  social:
    linkedin: https://www.linkedin.com/en/ryan-harden/
    github: https://github.com/AirForceGrads

# Build settings
theme: null # Replace with your theme's name
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Markdown settings
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: true

gems:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem

# Exclude files from the build
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - _config.yml

# Custom theme settings
custom_theme_settings:
  color_scheme: light
  font: "Inconsolata"
  header_image: "/assets/images/header.jpg"
